# Generated by Django 5.1.2 on 2024-12-30 12:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_publish_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
